Document: powerfuzzer
Title: Debian powerfuzzer Manual
Author: <insert document author here>
Abstract: This manual describes what powerfuzzer is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/powerfuzzer/powerfuzzer.sgml.gz

Format: postscript
Files: /usr/share/doc/powerfuzzer/powerfuzzer.ps.gz

Format: text
Files: /usr/share/doc/powerfuzzer/powerfuzzer.text.gz

Format: HTML
Index: /usr/share/doc/powerfuzzer/html/index.html
Files: /usr/share/doc/powerfuzzer/html/*.html
